import type { Metadata } from "next";
import { Inter, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { ThemeProvider } from "next-themes";
import MainLayout from "./components/MainLayout/MainLayout";

const theme_font = Red_Hat_Display({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={theme_font.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <ReduxProvider>
            <MainLayout>{children}</MainLayout>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
